### ISSUE TITLE
error while loading shared libraries: libtesseract.so.3

### ISSUE THREAD

**Issue by ljkeller** [renesas-rz/rzv_ai_sdk#11]
Hi, I'm trying to run [Q06_expiry_date_detection](https://github.com/renesas-rz/rzv_ai_sdk/tree/main/Q06_expiry_date_detection) on RZV2L (Trying to port some demo applications to RZBoard V2L)

## Problem
After building the demo in the AI SDK Docker container (Should be AI SDK 2.0+), I copied the `libtvm` .so and `exe/ `directories over to my RZBoard V2L. I'm experiencing this runtime error: 

> ./date_extraction_usb: error while loading shared libraries: libtesseract.so.3: cannot open shared object file: No such file or directory

**What is the install procedure for getting tesserract and related runtime dependencies installed to my device?** I copied libtesseract.so.3.0.5 from my AI SDK docker image to my RZBoard, but that wasn't sufficient. After changing the name to /usr/lib64/libtesseract.so.3, I ran into a new shared library error: 

> /date_extraction_usb: error while loading shared libraries: liblept.so.5: cannot open shared object file: No such file or directory

It seems [Application: Deploy Stage](https://github.com/renesas-rz/rzv_ai_sdk/tree/main/Q06_expiry_date_detection#application-deploy-stage) needs some more information.

Thank you!

**Comment by wk-mnA** [comment]
@ljkeller 
Thank you for reporting.
The tesseract is included in the AI SDK and you are not required to copy any tesseract library to the board.
Could you provide following information?
- AI SDK version (you can provide the zip filename that you downloaded from our website, i.e., RTK0EF0160F02100SJ.zip)
- The commit ID of repository you cloned for Q06_expiry_date_detection

**Comment by wk-mnA** [comment]
@ljkeller 
Close the issue since it has been inactive since January.
Please try the latest environment (RZ/V2L AI SDK v5.00), which is released in October.

Please re-open the issue if you have any problems.
